load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "2025day1",
    srcs = ["2025day1.cc"],
)

cc_binary(
    name = "2025day2",
    srcs = ["2025day2.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2025day3",
    srcs = ["2025day3.cc"],
)

cc_binary(
    name = "2025day4",
    srcs = ["2025day4.cc"],
}
