load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "2024day1",
    srcs = ["2024day1.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2024day2",
    srcs = ["2024day2.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2024day3",
    srcs = ["2024day3.cc"],
)

cc_binary(
    name = "2024day4",
    srcs = ["2024day4.cc"],
)

cc_binary(
    name = "2024day5",
    srcs = ["2024day5.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2024day6",
    srcs = ["2024day6.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2024day7",
    srcs = ["2024day7.cc"],
    deps = ["@com_google_absl//absl/strings"],
)

cc_binary(
    name = "2024day8",
    srcs = ["2024day8.cc"],
    deps = ["@com_google_absl//absl/strings"],
)
